config/routes.rb
Rails.application.routes.draw do
  root 'chat_rooms#index'
  get 'users/show/:id' => 'users#show'
  get 'users/edit'
  patch 'users/update'
  patch 'messages/destroy'
  devise_for :users
  resources :chat_rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  #対応するデータベースのテーブルを用意しない
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages,dependent: :destroy
  validates :title, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  validates :body, presence: true, length: {minimum: 2, maximum: 1000}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  validates :first_name,:last_name,:email,:password,:password_confirmation,presence: true
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception #セキュリティトークンが自動的に含まれる
  before_action :authenticate_user!, except: :index
  before_action :configure_permitted_parameters, if: :devise_controller? #deviseを使う画面に移動したときに動く

  private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :image])
    end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
    
    def index
        #Decorator付きのオブジェクトを渡す
        @chat_rooms = ChatRoomDecorator.decorate_collection(ChatRoom.all) 
    end

    def show
        @chat_room = ChatRoom.find(params[:id])
        @json_object = ChatRoomsSerializer.new(@chat_room).as_json
    end
    
    def new
        @chat_room = ChatRoom.new
    end
    
    def create
        @chat_room = current_user.chat_rooms.new(chat_room_params)
    
      if @chat_room.save
          redirect_to chat_rooms_path
      else
          render 'new'
      end
    end

    def destroy
      chatroom = ChatRoom.find(params[:id])
      	if chatroom.user_id == current_user.id
           chatroom.destroy
           redirect_to action: 'index'
        else
           redirect_to action: 'index'
        end
    end

    private
    def chat_room_params
        params.require(:chat_room).permit(:title)
    end
end

app/controllers/messages_controller.rb
class MessageController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if current_user.update(update_params) 
      redirect_to :action => "show", :id => current_user.id
    else
      redirect_to :action => "edit", :id => current_user.id
    end
  end
  
  private
    def update_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat_rooms/index.html.erb
<body>

	<section class="home page layer">
	<h1>Chat Place</h1>
　</section>　

<nav class="layer">
  <ul>
<div class="top_menu">
  <li>
  <%if user_signed_in?%>
    <%= link_to "My Account", "/users/show/#{current_user.id}",class:"menu"%>
    <% else %>
    <%= "Your Account??"%>
    <% end %>
  </li>
  
  <li>
    <% if user_signed_in? %>
      <%= link_to 'Log Out', destroy_user_session_path, method: :delete,class:"menu"%>
      <%else%>
     <%= link_to 'Sign In',new_user_session_path, method: :post,class:"menu"%>
      <% end %>
  </li>
   <li>
     <%= link_to 'Create Chatroom', new_chat_room_path, class:"menu"%>
  </li>
</div>

<div class="chatroom">
<% @chat_rooms.each do |chat_room| %>
<li>
  <div class="chat_rooms">
        <div><%= chat_room.title %></div>
        <div><%= link_to "Enter", chat_room_path(chat_room), class: "menu"  %>
        <%= link_to "Delete", chat_room_path(chat_room),method: :delete, class: "menu"  %></div>
        <div>--Owner--    
        <%= link_to chat_room.owner, "/users/show/#{chat_room.user_id}",id:"owner", class: "menu" %></div>
      <%= chat_room.created_at %>
</div>
</li>
<% end %>
</div>

</ul>
</nav>
</body>

app/views/chat_rooms/new.html.erb
<div class="nav_menus">
<h2 class="main_text">
  Create Chat Room
  <br/>
</h2>
<%= form_for @chat_room do |f| %>
  <div class="form-group">
  <%= f.label :title, class:"nav_menu" %>
  <%= f.text_field :title, autofocus: true, class: "creatroom", maxlength:"15" %>
  <%= f.submit "Save",class:"save_menu"%>
  <%= link_to "Back", chat_rooms_path, class:"nav_text" %>
  </div>
<% end %>
</div>

app/views/chat_rooms/show.html.erb
<div class="chat_title_text">
  <%= @chat_room.title %>
  </div>
  <br/>
  <div class="chat_show_back_botton">
    <%= link_to 'Back', chat_rooms_path, class: "chat_show_back" %>
  </div>

<%= react_component('ChatRoom', { chat_room: @json_object }) %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="bg"></div>
    <div class="bg bg2"></div>
    <div class="bg bg3"></div>
      <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class="nav_menus">
<h2 class="main_text">User Edit</h2>
<%= form_for @user, url: users_update_path do |f| %>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="actions">
    <%= f.submit class:"user-menu-update" %>
  </div>
<% end %>
  <%= link_to 'bakc', chat_rooms_path, class: 'back_text' %>
</div>

app/views/users/show.html.erb
<div class="user_show">
    <img src=<%= @user.image %> class="user_icon_image">
    <p class="user_name"><%= @user.first_name + " " + @user.last_name %></p>
    <br/>
	<%if @user.id == current_user.id%>
    <%= link_to 'edit',users_edit_path(id: @user.id), class: 'back_text' %>
  <%end%>
    <%= link_to 'bakc', chat_rooms_path, class: 'back_text' %>
</div>